/// <reference types = "cypress" />


import faker from 'faker'
describe('Registration', () => {
  const email = faker.internet.email()
  const password = faker.internet.password()
    before(() => {
      cy.visit('http://automationpractice.com/index.php')
      cy.get('.login').click()
      cy.get('input[name=email_create]').type(email)
      cy.get('#SubmitCreate > span').click()
      Cypress.config('defaultCommandTimeout', 10000);
      cy.get('#id_gender1').click()
      cy.get('#customer_firstname').type('Kamil')
      cy.get('#customer_lastname').type('Labedzki')
      cy.get('input[name="passwd"]').type(password)
      cy.get("#days").select('2')
      cy.get('#months').select('2')
      cy.get('#years').select('1977')
      cy.get('#company').type('dasdasfasd')
      cy.get('#address1').type('asfaisjs')
      cy.get('#address2').type('asdfgasdg')
      cy.get('#city').type('asdfsg')
      cy.get('#id_state').select('5')
      cy.get('#postcode').type('12345')
      cy.get('#phone').type('123456789')
      cy.get('#phone_mobile').type('123456789')
      cy.get('#submitAccount > span').click()
      cy.get('.logo').click()
      cy.get('.logout').click()
  })
 beforeEach(() =>{
  cy.get('.logo').click()  
  cy.get('.login').click()
  cy.get('#email').type(email)
  cy.get('#passwd').type(password)
  cy.get('#SubmitLogin > span').click()
  cy.get('.logo').click()
})
  it('Add dress they buy her', () => {
    cy.get('.sf-menu > :nth-child(3) > a').click()
    cy.get('.right-block').trigger('mouseover')
    cy.get('span').contains('Add to cart').click()
    cy.get('.button-container > .button-medium > span').click()
    cy.get('.cart_navigation > .button > span').click()
    cy.get('.cart_navigation > .button > span').click()
    cy.get('#cgv').click()
    cy.get('.cart_navigation > .button > span').click()
    cy.get('.bankwire').click()
    cy.get('#cart_navigation > .button > span').click()
  })
   it('Add 3 different size dresses, then subtracting one item at a time ', () => {
        
        cy.get('.sf-menu > :nth-child(2) > .sf-with-ul').click()
        cy.get(':nth-child(2) > .subcategory-image > .img > .replace-2x').click()
        cy.get('.right-block').trigger('mousemove').click()
        cy.get('span').contains('Add to cart').click()
        cy.get('.continue > span').click()
        cy.get('.right-block').trigger('mouseover')
        cy.get('span').contains('More').click()
        Cypress.config('defaultCommandTimeout', 10000);
        cy.get('input[id="quantity_wanted"]').clear()
        cy.get('input[id="quantity_wanted"]').type('3')
        cy.get('select[id="group_1"]').select('M')
        cy.get('span').contains('Add to cart').click()
        cy.get('.continue > span').click()
        cy.get('input[id="quantity_wanted"]').clear()
        cy.get('input[id="quantity_wanted"]').type('5')
        cy.get('select[id="group_1"]').select('L')
        cy.get('span').contains('Add to cart').click()
        cy.get('.button-medium > span').click()
        cy.get('a[id="4_16_0_0"]').click()
        cy.get('#cart_quantity_down_4_17_0_0 > span').click()
        cy.get('#cart_quantity_down_4_18_0_0 > span').click()
      })
  it('Ad dress to wishlist',() =>{
   
    cy.get('.sf-menu > :nth-child(2) > .sf-with-ul').click()
    cy.get('.last-line.first-item-of-tablet-line > .product-container > .right-block').trigger('mouseover')
    cy.get('div > a[class="addToWishlist wishlistProd_7"]').click()
    cy.get('.fancybox-item').click()
   })
   it('Send emial to site ovner',()=>{
   
    cy.get('#contact-link > a').click()
    cy.get('#message').type("Letter message")
    cy.get('select[id="id_contact"]').select('2')
    cy.get('#email').type(email)
    cy.get('input[id="id_order"]').type('1')
    cy.get('#submitMessage > span').click()
  })
  
  it('Add one iteam from four categories',()=>{
    cy.visit('http://automationpractice.com/index.php')  
    Cypress.config('defaultCommandTimeout', 15000);
    cy.get('.sf-menu > :nth-child(3) > a').click()
    cy.get('.right-block').trigger('mouseover')
    cy.get('span').contains('Add to cart').click({force: true})
    cy.get('.continue > span').click()
    cy.get('.logo').click()
    cy.get('.sf-menu > :nth-child(2) > .sf-with-ul').click()
    cy.get(':nth-child(2) > .subcategory-image > .img > .replace-2x').click()
    cy.get('.right-block').trigger('mouseover')
    cy.get('span').contains('Add to cart').click({force: true})
    cy.get('.continue > span').click()
    cy.get('.logo').click()
    cy.get('.sf-menu > :nth-child(2) > .sf-with-ul').click()
    cy.get(':nth-child(1) > .subcategory-image > .img > .replace-2x').click()
    cy.get('.right-block').trigger('mouseover')
    cy.get('span').contains('Add to cart').click({force: true})
    cy.get('.continue > span').click()
    cy.get('.logo').click()
    cy.get('.sf-menu > :nth-child(2) > .sf-with-ul').click()
    cy.get(':nth-child(3) > .subcategory-image > .img > .replace-2x').click()
    cy.get('.first-in-line > .product-container > .right-block').trigger('mouseover')
    cy.get('span').contains('Add to cart').click({force: true})
    cy.get('.continue > span').click()
  })
})

